/* imports_exec.c -- resolver table for libc++_shared.so + libexecutive_android.so
 *
 * GENERATED by tools/gen_imports.py. Do not hand-edit the bulk of it;
 * re-run the generator and re-apply intentional overrides at the bottom.
 *
 * libexecutive_android.so is linked BIND_NOW, so every entry has to resolve
 * before the first call into the module. A gap is a load-time abort.
 *
 * Coverage: 238 symbols
 *     37  GL            -> switch-mesa
 *     41  NDK / loader  -> our code
 *     78  bionic shims  -> libc_shim.c
 *     82  newlib passthrough
 */

#define _GNU_SOURCE
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <strings.h>
#include <malloc.h>
#include <unistd.h>
#include <fcntl.h>
#include <ctype.h>
#include <math.h>
#include <pthread.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>
#include <errno.h>
#include <locale.h>
#include <setjmp.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <dirent.h>
#include <GLES2/gl2.h>

#include "so_util.h"
#include "libc_shim.h"
#include "compat_stubs.h"
#include "imports_helpers.h"
#include "exec_asset.h"
#include "exec_bitmap.h"
#include "exec_log.h"
#include "exec_shim.h"
#include "exec_bionic.h"
#include "exec_io.h"
#include "exec_rwlock.h"

DynLibFunction dynlib_functions[] = {
  /* ---- GL -> switch-mesa ---- */
  { "glActiveTexture",              (uintptr_t)&glActiveTexture },
  { "glAttachShader",               (uintptr_t)&glAttachShader },
  { "glBindTexture",                (uintptr_t)&glBindTexture },
  { "glBlendFunc",                  (uintptr_t)&glBlendFunc },
  { "glClear",                      (uintptr_t)&glClear },
  { "glClearColor",                 (uintptr_t)&glClearColor },
  { "glCompileShader",              (uintptr_t)&glCompileShader },
  { "glCreateProgram",              (uintptr_t)&glCreateProgram },
  { "glCreateShader",               (uintptr_t)&glCreateShader },
  { "glDeleteShader",               (uintptr_t)&glDeleteShader },
  { "glDeleteTextures",             (uintptr_t)&glDeleteTextures },
  { "glDisable",                    (uintptr_t)&glDisable },
  { "glDisableVertexAttribArray",   (uintptr_t)&glDisableVertexAttribArray },
  { "glDrawElements",               (uintptr_t)&glDrawElements },
  { "glEnable",                     (uintptr_t)&glEnable },
  { "glEnableVertexAttribArray",    (uintptr_t)&glEnableVertexAttribArray },
  { "glGenTextures",                (uintptr_t)&glGenTextures },
  { "glGetAttribLocation",          (uintptr_t)&glGetAttribLocation },
  { "glGetProgramInfoLog",          (uintptr_t)&glGetProgramInfoLog },
  { "glGetProgramiv",               (uintptr_t)&glGetProgramiv },
  { "glGetShaderInfoLog",           (uintptr_t)&glGetShaderInfoLog },
  { "glGetShaderiv",                (uintptr_t)&glGetShaderiv },
  { "glGetUniformLocation",         (uintptr_t)&glGetUniformLocation },
  { "glLinkProgram",                (uintptr_t)&glLinkProgram },
  { "glPixelStorei",                (uintptr_t)&glPixelStorei },
  { "glReadPixels",                 (uintptr_t)&glReadPixels },
  { "glScissor",                    (uintptr_t)&glScissor },
  { "glShaderSource",               (uintptr_t)&glShaderSource },
  { "glTexImage2D",                 (uintptr_t)&glTexImage2D },
  { "glTexParameteri",              (uintptr_t)&glTexParameteri },
  { "glUniform1f",                  (uintptr_t)&glUniform1f },
  { "glUniform1i",                  (uintptr_t)&glUniform1i },
  { "glUniform4f",                  (uintptr_t)&glUniform4f },
  { "glUniformMatrix4fv",           (uintptr_t)&glUniformMatrix4fv },
  { "glUseProgram",                 (uintptr_t)&glUseProgram },
  { "glVertexAttribPointer",        (uintptr_t)&glVertexAttribPointer },
  { "glViewport",                   (uintptr_t)&glViewport },

  /* ---- NDK / loader -> our code ---- */
  { "AAssetManager_fromJava",       (uintptr_t)&AAssetManager_fromJava },
  { "AAssetManager_open",           (uintptr_t)&AAssetManager_open },
  { "AAsset_close",                 (uintptr_t)&AAsset_close },
  { "AAsset_getLength",             (uintptr_t)&AAsset_getLength },
  { "AAsset_read",                  (uintptr_t)&AAsset_read },
  { "AndroidBitmap_getInfo",        (uintptr_t)&AndroidBitmap_getInfo },
  { "AndroidBitmap_lockPixels",     (uintptr_t)&AndroidBitmap_lockPixels },
  { "AndroidBitmap_unlockPixels",   (uintptr_t)&AndroidBitmap_unlockPixels },
  { "__android_log_print",          (uintptr_t)&exec_log_print },
  { "__cxa_atexit",                 (uintptr_t)&__cxa_atexit_fake },
  { "__cxa_finalize",               (uintptr_t)&exec_cxa_finalize },
  { "__errno",                      (uintptr_t)&__errno },
  { "__register_atfork",            (uintptr_t)&exec_register_atfork },
  { "__sF",                         (uintptr_t)&fake_sF },
  { "__stack_chk_fail",             (uintptr_t)&__stack_chk_fail_fake },
  { "__system_property_get",        (uintptr_t)&exec_system_property_get },
  { "android_set_abort_message",    (uintptr_t)&exec_set_abort_message },
  { "clock_gettime",                (uintptr_t)&clock_gettime_bionic },
  { "close",                        (uintptr_t)&close_locked },
  { "closelog",                     (uintptr_t)&ret0_i },
  { "dl_iterate_phdr",              (uintptr_t)&so_dl_iterate_phdr },
  { "fchmodat",                     (uintptr_t)&exec_fchmodat },
  { "fclose",                       (uintptr_t)&fclose_locked },
  { "fdopendir",                    (uintptr_t)&exec_fdopendir },
  { "fopen",                        (uintptr_t)&fopen_locked },
  { "fread",                        (uintptr_t)&fread_locked },
  { "fseek",                        (uintptr_t)&fseek_locked },
  { "ftell",                        (uintptr_t)&ftell_locked },
  { "fwrite",                       (uintptr_t)&fwrite_locked },
  { "getauxval",                    (uintptr_t)&exec_getauxval },
  { "ioctl",                        (uintptr_t)&exec_ioctl },
  { "openlog",                      (uintptr_t)&ret0_i },
  { "pthread_mutexattr_destroy",    (uintptr_t)&ret0_i },
  { "pthread_rwlock_rdlock",        (uintptr_t)&exec_rwlock_rdlock },
  { "pthread_rwlock_unlock",        (uintptr_t)&exec_rwlock_unlock },
  { "pthread_rwlock_wrlock",        (uintptr_t)&exec_rwlock_wrlock },
  { "read",                         (uintptr_t)&read_locked },
  { "sendfile",                     (uintptr_t)&exec_sendfile },
  { "setlocale",                    (uintptr_t)&setlocale_bionic },
  { "syslog",                       (uintptr_t)&ret0_i },
  { "utimensat",                    (uintptr_t)&exec_utimensat },

  /* ---- bionic shims -> libc_shim.c ---- */
  { "__ctype_get_mb_cur_max",       (uintptr_t)&__ctype_get_mb_cur_max_fake },
  { "__cxa_thread_atexit_impl",     (uintptr_t)&__cxa_thread_atexit_impl_fake },
  { "__strcpy_chk",                 (uintptr_t)&__strcpy_chk_fake },
  { "__strlen_chk",                 (uintptr_t)&__strlen_chk_fake },
  { "__vsprintf_chk",               (uintptr_t)&__vsprintf_chk_fake },
  { "closedir",                     (uintptr_t)&closedir_fake },
  { "fflush",                       (uintptr_t)&fflush_fake },
  { "fileno",                       (uintptr_t)&fileno_fake },
  { "fprintf",                      (uintptr_t)&fprintf_fake },
  { "fputc",                        (uintptr_t)&fputc_fake },
  { "freelocale",                   (uintptr_t)&freelocale_fake },
  { "fseeko",                       (uintptr_t)&fseeko_fake },
  { "fstat",                        (uintptr_t)&fstat_fake },
  { "ftello",                       (uintptr_t)&ftello_fake },
  { "getc",                         (uintptr_t)&getc_fake },
  { "getcwd",                       (uintptr_t)&getcwd_fake },
  { "getenv",                       (uintptr_t)&getenv_fake },
  { "iswalpha_l",                   (uintptr_t)&iswalpha_l_fake },
  { "iswblank_l",                   (uintptr_t)&iswblank_l_fake },
  { "iswcntrl_l",                   (uintptr_t)&iswcntrl_l_fake },
  { "iswdigit_l",                   (uintptr_t)&iswdigit_l_fake },
  { "iswlower_l",                   (uintptr_t)&iswlower_l_fake },
  { "iswprint_l",                   (uintptr_t)&iswprint_l_fake },
  { "iswpunct_l",                   (uintptr_t)&iswpunct_l_fake },
  { "iswspace_l",                   (uintptr_t)&iswspace_l_fake },
  { "iswupper_l",                   (uintptr_t)&iswupper_l_fake },
  { "iswxdigit_l",                  (uintptr_t)&iswxdigit_l_fake },
  { "lstat",                        (uintptr_t)&lstat_fake },
  { "mbsnrtowcs",                   (uintptr_t)&mbsnrtowcs_fake },
  { "mkdir",                        (uintptr_t)&mkdir_fake },
  { "newlocale",                    (uintptr_t)&newlocale_fake },
  { "open",                         (uintptr_t)&open_fake },
  { "openat",                       (uintptr_t)&openat_fake },
  { "pathconf",                     (uintptr_t)&pathconf_fake },
  { "posix_memalign",               (uintptr_t)&posix_memalign_fake },
  { "pthread_cond_broadcast",       (uintptr_t)&pthread_cond_broadcast_fake },
  { "pthread_cond_destroy",         (uintptr_t)&pthread_cond_destroy_fake },
  { "pthread_cond_signal",          (uintptr_t)&pthread_cond_signal_fake },
  { "pthread_cond_timedwait",       (uintptr_t)&pthread_cond_timedwait_fake },
  { "pthread_cond_wait",            (uintptr_t)&pthread_cond_wait_fake },
  { "pthread_getspecific",          (uintptr_t)&pthread_getspecific_fake },
  { "pthread_join",                 (uintptr_t)&pthread_join_fake },
  { "pthread_key_create",           (uintptr_t)&pthread_key_create_fake },
  { "pthread_key_delete",           (uintptr_t)&pthread_key_delete_fake },
  { "pthread_mutex_destroy",        (uintptr_t)&pthread_mutex_destroy_fake },
  { "pthread_mutex_init",           (uintptr_t)&pthread_mutex_init_fake },
  { "pthread_mutex_lock",           (uintptr_t)&pthread_mutex_lock_fake },
  { "pthread_mutex_trylock",        (uintptr_t)&pthread_mutex_trylock_fake },
  { "pthread_mutex_unlock",         (uintptr_t)&pthread_mutex_unlock_fake },
  { "pthread_mutexattr_init",       (uintptr_t)&pthread_mutexattr_init_fake },
  { "pthread_mutexattr_settype",    (uintptr_t)&pthread_mutexattr_settype_fake },
  { "pthread_once",                 (uintptr_t)&pthread_once_fake },
  { "pthread_setspecific",          (uintptr_t)&pthread_setspecific_fake },
  { "readdir",                      (uintptr_t)&readdir_fake },
  { "realpath",                     (uintptr_t)&realpath_fake },
  { "sincos",                       (uintptr_t)&sincos_fake },
  { "sincosf",                      (uintptr_t)&sincosf_fake },
  { "stat",                         (uintptr_t)&stat_fake },
  { "statvfs",                      (uintptr_t)&statvfs_fake },
  { "strcoll_l",                    (uintptr_t)&strcoll_l_fake },
  { "strerror_r",                   (uintptr_t)&strerror_r_fake },
  { "strftime_l",                   (uintptr_t)&strftime_l_fake },
  { "strtold_l",                    (uintptr_t)&strtold_l_fake },
  { "strtoll_l",                    (uintptr_t)&strtoll_l_fake },
  { "strtoull_l",                   (uintptr_t)&strtoull_l_fake },
  { "strxfrm_l",                    (uintptr_t)&strxfrm_l_fake },
  { "syscall",                      (uintptr_t)&syscall_fake },
  { "sysconf",                      (uintptr_t)&sysconf_fake },
  { "towlower_l",                   (uintptr_t)&towlower_l_fake },
  { "towupper_l",                   (uintptr_t)&towupper_l_fake },
  { "truncate",                     (uintptr_t)&truncate_fake },
  { "ungetc",                       (uintptr_t)&ungetc_fake },
  { "unlinkat",                     (uintptr_t)&unlinkat_fake },
  { "uselocale",                    (uintptr_t)&uselocale_fake },
  { "vfprintf",                     (uintptr_t)&vfprintf_fake },
  { "wcscoll_l",                    (uintptr_t)&wcscoll_l_fake },
  { "wcsnrtombs",                   (uintptr_t)&wcsnrtombs_fake },
  { "wcsxfrm_l",                    (uintptr_t)&wcsxfrm_l_fake },

  /* ---- newlib passthrough ---- */
  { "abort",                        (uintptr_t)&abort },
  { "acosf",                        (uintptr_t)&acosf },
  { "asin",                         (uintptr_t)&asin },
  { "atan",                         (uintptr_t)&atan },
  { "atan2",                        (uintptr_t)&atan2 },
  { "atan2f",                       (uintptr_t)&atan2f },
  { "btowc",                        (uintptr_t)&btowc },
  { "calloc",                       (uintptr_t)&calloc },
  { "chdir",                        (uintptr_t)&chdir },
  { "cos",                          (uintptr_t)&cos },
  { "expf",                         (uintptr_t)&expf },
  { "fchmod",                       (uintptr_t)&fchmod },
  { "fmod",                         (uintptr_t)&fmod },
  { "fmodf",                        (uintptr_t)&fmodf },
  { "fputwc",                       (uintptr_t)&fputwc },
  { "free",                         (uintptr_t)&free },
  { "ftruncate",                    (uintptr_t)&ftruncate },
  { "gettimeofday",                 (uintptr_t)&gettimeofday },
  { "getwc",                        (uintptr_t)&getwc },
  { "isatty",                       (uintptr_t)&isatty },
  { "link",                         (uintptr_t)&link },
  { "localeconv",                   (uintptr_t)&localeconv },
  { "malloc",                       (uintptr_t)&malloc },
  { "mbrlen",                       (uintptr_t)&mbrlen },
  { "mbrtowc",                      (uintptr_t)&mbrtowc },
  { "mbsrtowcs",                    (uintptr_t)&mbsrtowcs },
  { "mbtowc",                       (uintptr_t)&mbtowc },
  { "memchr",                       (uintptr_t)&memchr },
  { "memcmp",                       (uintptr_t)&memcmp },
  { "memcpy",                       (uintptr_t)&memcpy },
  { "memmove",                      (uintptr_t)&memmove },
  { "memset",                       (uintptr_t)&memset },
  { "modf",                         (uintptr_t)&modf },
  { "nanosleep",                    (uintptr_t)&nanosleep },
  { "opendir",                      (uintptr_t)&opendir },
  { "pow",                          (uintptr_t)&pow },
  { "pthread_detach",               (uintptr_t)&pthread_detach },
  { "pthread_self",                 (uintptr_t)&pthread_self },
  { "rand",                         (uintptr_t)&rand },
  { "readlink",                     (uintptr_t)&readlink },
  { "realloc",                      (uintptr_t)&realloc },
  { "remove",                       (uintptr_t)&remove },
  { "rename",                       (uintptr_t)&rename },
  { "setenv",                       (uintptr_t)&setenv },
  { "sin",                          (uintptr_t)&sin },
  { "sinf",                         (uintptr_t)&sinf },
  { "snprintf",                     (uintptr_t)&snprintf },
  { "sscanf",                       (uintptr_t)&sscanf },
  { "strcasecmp",                   (uintptr_t)&strcasecmp },
  { "strcmp",                       (uintptr_t)&strcmp },
  { "strcpy",                       (uintptr_t)&strcpy },
  { "strlen",                       (uintptr_t)&strlen },
  { "strncat",                      (uintptr_t)&strncat },
  { "strncmp",                      (uintptr_t)&strncmp },
  { "strrchr",                      (uintptr_t)&strrchr },
  { "strtod",                       (uintptr_t)&strtod },
  { "strtof",                       (uintptr_t)&strtof },
  { "strtol",                       (uintptr_t)&strtol },
  { "strtold",                      (uintptr_t)&strtold },
  { "strtoll",                      (uintptr_t)&strtoll },
  { "strtoul",                      (uintptr_t)&strtoul },
  { "strtoull",                     (uintptr_t)&strtoull },
  { "swprintf",                     (uintptr_t)&swprintf },
  { "symlink",                      (uintptr_t)&symlink },
  { "time",                         (uintptr_t)&time },
  { "ungetwc",                      (uintptr_t)&ungetwc },
  { "vasprintf",                    (uintptr_t)&vasprintf },
  { "vprintf",                      (uintptr_t)&vprintf },
  { "vsnprintf",                    (uintptr_t)&vsnprintf },
  { "vsscanf",                      (uintptr_t)&vsscanf },
  { "wcrtomb",                      (uintptr_t)&wcrtomb },
  { "wcslen",                       (uintptr_t)&wcslen },
  { "wcstod",                       (uintptr_t)&wcstod },
  { "wcstof",                       (uintptr_t)&wcstof },
  { "wcstol",                       (uintptr_t)&wcstol },
  { "wcstold",                      (uintptr_t)&wcstold },
  { "wcstoll",                      (uintptr_t)&wcstoll },
  { "wcstoul",                      (uintptr_t)&wcstoul },
  { "wcstoull",                     (uintptr_t)&wcstoull },
  { "wctob",                        (uintptr_t)&wctob },
  { "wmemchr",                      (uintptr_t)&wmemchr },
  { "wmemcmp",                      (uintptr_t)&wmemcmp },

};

const size_t dynlib_numfunctions = sizeof(dynlib_functions) / sizeof(dynlib_functions[0]);

/* dlsym() backing for the loaded modules. libc_shim.c calls this from
 * its dlsym shim, so the table doubles as the symbol namespace the
 * modules see. */
uintptr_t dynlib_find_export(const char *name) {
  DynLibFunction *f = so_find_import(dynlib_functions,
                                     (int)dynlib_numfunctions, name);
  return f ? f->func : 0;
}
